#!/bin/bash
#SBATCH --job-name=OTFML_Scaled
#SBATCH --partition=small_gpu8
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=72
#SBATCH --gpus-per-node=8
#SBATCH --gpus=8
#SBATCH --nodelist=gpu08
#SBATCH --time=23:30:00
#SBATCH --mail-type=NONE 
#SBATCH --output=%x_%j.out

module purge
module load anaconda3/2021.11
module load cuda
eval "$(conda shell.bash hook)"
conda activate MACE
conda info --envs

module use --append path/to/VASP/Module/Files
module load VASP 2>&1
python -u MLFFProc.py