CodePath: './'
TargetPath: './tests/'
DFTResourceManager: SLURM
NNPResourceManager: SLURM
FFType: Ensemble
n_models: 8
dev_list: [0,1,2,3,4,5,6,7] 
NNPBuilder: MACE #SpiceNequIP
constructor_args: [0.5]
DFTCode: vasp_std
DFTProcSubmitFile: VASPProc_Submit
NNPProcSubmitFile: NNPProc_Submit
ErrorThreshold: 0.5
